/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 27/04/2018 07:48:16
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       16000000
#define MX_FCLKCortexFreq_Value                 16000000
#define MX_CortexFreq_Value                     16000000
#define MX_AHBFreq_Value                        16000000
#define MX_APB1Freq_Value                       16000000
#define MX_APB2Freq_Value                       16000000
#define MX_APB1TimFreq_Value                    16000000
#define MX_APB2TimFreq_Value                    16000000
#define MX_EthernetFreq_Value                   16000000
#define MX_CECFreq_Value                        32786
#define MX_LCDTFToutputFreq_Value               48000000
#define MX_I2C1Freq_Value                       16000000
#define MX_I2C2Freq_Value                       16000000
#define MX_I2C3Freq_Value                       16000000
#define MX_I2C4Freq_Value                       16000000
#define MX_I2SFreq_Value                        96000000
#define MX_SAI1Freq_Value                       96000000
#define MX_SAI2Freq_Value                       96000000
#define MX_SDMMCFreq_Value                      16000000
#define MX_RTCFreq_Value                        32000
#define MX_USART1Freq_Value                     16000000
#define MX_USART2Freq_Value                     16000000
#define MX_USART3Freq_Value                     16000000
#define MX_UART4Freq_Value                      16000000
#define MX_UART5Freq_Value                      16000000
#define MX_UART8Freq_Value                      16000000
#define MX_UART7Freq_Value                      16000000
#define MX_USART6Freq_Value                     16000000
#define MX_USBFreq_Value                        96000000
#define MX_WatchDogFreq_Value                   32000
#define MX_LPTIM1Freq_Value                     16000000
#define MX_SPDIFRXFreq_Value                    96000000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    16000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA0/WKUP */
#define MX_ADCx_IN0_Pin                         PA0_WKUP
#define MX_ADCx_IN0_GPIOx                       GPIOA
#define MX_ADCx_IN0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN0_GPIO_Pin                    GPIO_PIN_0
#define MX_ADCx_IN0_GPIO_Mode                   GPIO_MODE_ANALOG

/* NVIC Configuration */

/* NVIC ADC_IRQn */
#define MX_ADC_IRQn_interruptPremptionPriority  0
#define MX_ADC_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ADC_IRQn_Subriority                  0

/*-------------------------------- ADC2       --------------------------------*/

#define MX_ADC2                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ADCx_IN1_Pin                         PA1
#define MX_ADCx_IN1_GPIOx                       GPIOA
#define MX_ADCx_IN1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN1_GPIO_Pin                    GPIO_PIN_1
#define MX_ADCx_IN1_GPIO_Mode                   GPIO_MODE_ANALOG

/* NVIC Configuration */

/* NVIC ADC_IRQn */
#define MX_ADC_IRQn_interruptPremptionPriority  0
#define MX_ADC_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ADC_IRQn_Subriority                  0

/*-------------------------------- ADC3       --------------------------------*/

#define MX_ADC3                                 1

/* GPIO Configuration */

/* Pin PA2 */
#define MX_ADCx_IN2_Pin                         PA2
#define MX_ADCx_IN2_GPIOx                       GPIOA
#define MX_ADCx_IN2_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN2_GPIO_Pin                    GPIO_PIN_2
#define MX_ADCx_IN2_GPIO_Mode                   GPIO_MODE_ANALOG

/* NVIC Configuration */

/* NVIC ADC_IRQn */
#define MX_ADC_IRQn_interruptPremptionPriority  0
#define MX_ADC_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ADC_IRQn_Subriority                  0

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PB14 */
#define MX_PB14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PB14_Pin                             PB14
#define MX_PB14_GPIOx                           GPIOB
#define MX_PB14_PinState                        GPIO_PIN_RESET
#define MX_PB14_GPIO_PuPd                       GPIO_NOPULL
#define MX_PB14_GPIO_Pin                        GPIO_PIN_14
#define MX_PB14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PB7 */
#define MX_PB7_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB7_Pin                              PB7
#define MX_PB7_GPIOx                            GPIOB
#define MX_PB7_PinState                         GPIO_PIN_RESET
#define MX_PB7_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB7_GPIO_Pin                         GPIO_PIN_7
#define MX_PB7_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PB0 */
#define MX_PB0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PB0_Pin                              PB0
#define MX_PB0_GPIOx                            GPIOB
#define MX_PB0_PinState                         GPIO_PIN_RESET
#define MX_PB0_GPIO_PuPd                        GPIO_NOPULL
#define MX_PB0_GPIO_Pin                         GPIO_PIN_0
#define MX_PB0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

